version: "3"
services:
  redis:
    container_name: dba_redis
    hostname: local.dba_redis

    image: bitnami/redis:latest

    tty: true
    #env_file:
    #  - ./docker/env/redis.env

    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7000

    ports:
      - '7000:7000'

    #working_dir: /app/sql

    #ports:
    #  - 3306:3306

    #volumes:
    #  - ./docker/volume/mysql:/var/lib/mysql
    #  - ./sql:/app/sql
    #  - ./docker/default:/docker-entrypoint-initdb.d

    #command: --init-file /docker-entrypoint-initdb.d/init.sql  #attention here

    networks:
      - dsi_server

networks:
  dsi_server:
    driver: bridge
